apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: rewards-studio-app
  name: rewards-studio-app
  namespace: rewards-studio
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: rewards-studio-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rewards-studio-app
    spec:
      containers:
        - name: rewards-studio
          image: 992382680272.dkr.ecr.eu-west-3.amazonaws.com/sandbox-dev-rewards-studio:main-00f67b2
          command: ["sh"]
          args: ["./entrypoint.sh"]
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 300m
              memory: 1Gi
          envFrom:
            - secretRef:
                name: rewards-studio-app
            - secretRef:
                name: rds-sandbox-dev-rewards-studio
          env:
            - name: DATABASE_URL
              value: postgresql://$(PGUSER):$(PGPASSWORD)@$(PGHOST):$(PGPORT)/$(PGDATABASE)
            - name: PHOSPHOR_ADMIN_API_URL
              value: https://admin-api.dev.phosphor.xyz
            - name: PHOSPHOR_PUBLIC_API_URL
              value: https://public-api.dev.phosphor.xyz
            - name: METAFI_API_URL
              value: https://accounts.api.cx.metamask.io
            - name: METAMASK_PORTFOLIO_URL
              value: https://dev.portfolio.metamask.io
            - name: PHOSPHOR_URL
              value: https://dev.phosphor.xyz
            - name: PHOSPHOR_ORG_ID
              value: 26ff48ce-4355-4c64-8589-a86461a46c38
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 5
