---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rewards-studio-app
  labels:
    app.kubernetes.io/name: rewards-studio-app
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: rewards-studio-app
    creationPolicy: Owner
  data:
  - secretKey: PHOSPHOR_ORG_APIKEY
    remoteRef:
      key: rewards-studio-app-secrets
      property: PHOSPHOR_ORG_APIKEY
  - secretKey: ADMIN_API_KEY
    remoteRef:
      key: rewards-studio-app-secrets
      property: ADMIN_API_KEY
