apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rewards-studio-app
  namespace: rewards-studio
  labels:
    app.kubernetes.io/name: rewards-studio-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rewards-studio-app