version: '3.9'
services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rewards
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d rewards"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./
      target: development
    command: ["./init.sh"]
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
